version: "3.8"
services:
  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: 'selenium-hub'
    ports:
      - "4444:4444"
    restart: always

  chrome:
    image: selenium/node-chrome:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Tokyo
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always

  python:
    build: './python-selenium'
    container_name: 'python-sb'
    working_dir: '/root/script/'
    entrypoint: "/bin/sh -c"
    command: '"service cron start && tail -f /dev/null"'
    depends_on:
      - chrome
    volumes:
      - ./script/:/root/script/
      - ./cred/:/root/cred/
    environment:
      - 'TZ=Asia/Tokyo'
    restart: always